name: Build BananaOS

on:
  push:
    branches:
      - main
      - IA32-EFI
      - x86_64
  pull_request:
    branches:
      - main
      - IA32-EFI
      - x86_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm gcc-multilib binutils \
                            grub-common grub-pc-bin xorriso mtools

    - name: Compile OS
      run: |
        make clean
        make

    # This renames the generic bananaos.img to include the branch name
    - name: Prepare Artifact Name
      run: mv bananaos.img bananaos-${{ github.ref_name }}.img

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # This names the download folder in GitHub
        name: bananaos-${{ github.ref_name }}-image
        # This points to the newly renamed file
        path: bananaos-${{ github.ref_name }}.img
